# ========================================================
# APPLICATION ENVIRONMENT CONFIGURATION
# ========================================================
appurl=http://localhost/opencart/
#appurl=http://192.168.1.70/opencart/

env_execute=local
#env_execute=remote

# ========================================================
# GLOBAL TEST EXECUTION DATA
# ========================================================
email=divakarbabuy8050@gmail.com
psw=OPENcart@123
TesterName=Divakarbabu Y
searchProductName=iPhone

# ========================================================
# SECURE SMTP EMAIL REPORTING PIPELINE CONFIGURATION
# ========================================================
sender_email=divakarbabuygithub@gmail.com
sender_app_password=psuz lqky abke shxt
email.recipients=divakarbabuy8050@gmail.com
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.sendReport=true